// frontend/src/components/data-table.tsx
import { useState } from 'react'

import {
  type ColumnDef,
  type SortingState,
  flexRender,
  getCoreRowModel,
  getSortedRowModel,
  useReactTable,
} from '@tanstack/react-table'

import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { cn } from '@/lib/utils'

type DataTableProps<TData> = {
  data: TData[]
  columns: ColumnDef<TData>[]
  emptyMessage: string
  onRowClick?: (row: TData) => void
}

export function DataTable<TData>({
  data,
  columns,
  emptyMessage,
  onRowClick,
}: DataTableProps<TData>) {
  const [sorting, setSorting] = useState<SortingState>([])
  const table = useReactTable({
    data,
    columns,
    state: { sorting },
    onSortingChange: setSorting,
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
  })

  return (
    <div className="overflow-hidden rounded-lg border border-border/40">
      <Table>
        <TableHeader className="bg-muted/25">
          {table.getHeaderGroups().map((headerGroup) => (
            <TableRow key={headerGroup.id} className="border-border/40 hover:bg-transparent">
              {headerGroup.headers.map((header) => (
                <TableHead key={header.id} className="text-[11px] font-medium tracking-wide text-muted-foreground">
                  {header.isPlaceholder
                    ? null
                    : flexRender(header.column.columnDef.header, header.getContext())}
                </TableHead>
              ))}
            </TableRow>
          ))}
        </TableHeader>
        <TableBody>
          {table.getRowModel().rows.length ? (
            table.getRowModel().rows.map((row, index) => (
              <TableRow
                key={row.id}
                className={cn(
                  'border-border/30 transition-colors duration-100',
                  onRowClick && 'cursor-pointer',
                  index % 2 === 1 && 'bg-muted/[0.08]',
                )}
                onClick={onRowClick ? () => onRowClick(row.original) : undefined}
              >
                {row.getVisibleCells().map((cell) => (
                  <TableCell key={cell.id} className="align-middle">
                    {flexRender(cell.column.columnDef.cell, cell.getContext())}
                  </TableCell>
                ))}
              </TableRow>
            ))
          ) : (
            <TableRow>
              <TableCell colSpan={columns.length} className="py-12 text-center text-sm text-muted-foreground">
                {emptyMessage}
              </TableCell>
            </TableRow>
          )}
        </TableBody>
      </Table>
    </div>
  )
}

// frontend/src/components/data-table.svelte
<script lang="ts" module>
  export type DataTableColumn<T> = {
    key: string
    header: string
    cell?: (row: T) => string
    snippet?: import('svelte').Snippet<[T]>
    headClass?: string
    cellClass?: string
  }
</script>

<script lang="ts" generics="T">
  import Table from '$components/ui/table.svelte'
  import TableBody from '$components/ui/table-body.svelte'
  import TableCell from '$components/ui/table-cell.svelte'
  import TableHead from '$components/ui/table-head.svelte'
  import TableHeader from '$components/ui/table-header.svelte'
  import TableRow from '$components/ui/table-row.svelte'

  type Props = {
    data: T[]
    columns: DataTableColumn<T>[]
    emptyMessage?: string
    onRowClick?: (row: T) => void
  }

  let { data, columns, emptyMessage = 'No data.', onRowClick }: Props = $props()
</script>

<div class="rounded-md border bg-muted/15">
  <Table>
    <TableHeader>
      <TableRow class="bg-muted/25 hover:bg-muted/25">
        {#each columns as column (column.key)}
          <TableHead class={column.headClass ?? 'text-[11px] font-medium tracking-wide'}>
            {column.header}
          </TableHead>
        {/each}
      </TableRow>
    </TableHeader>
    <TableBody>
      {#if data.length === 0}
        <TableRow>
          <TableCell class="text-center text-sm text-muted-foreground" colspan={columns.length}>
            {emptyMessage}
          </TableCell>
        </TableRow>
      {:else}
        {#each data as row, index (index)}
          <TableRow
            class={`${index % 2 === 1 ? 'bg-muted/[0.08]' : ''} ${onRowClick ? 'cursor-pointer' : ''}`}
            onclick={onRowClick ? () => onRowClick(row) : undefined}
          >
            {#each columns as column (column.key)}
              <TableCell class={column.cellClass}>
                {#if column.snippet}
                  {@render column.snippet(row)}
                {:else if column.cell}
                  {column.cell(row)}
                {:else}
                  {(row as Record<string, unknown>)[column.key] ?? ''}
                {/if}
              </TableCell>
            {/each}
          </TableRow>
        {/each}
      {/if}
    </TableBody>
  </Table>
</div>
